### ISSUE TITLE
Service Exception: AzureException: Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#1916] opened 2022-05-09 17:20 UTC
Filing bug with service exception information. These were bugs were detected by the new Azure Monitor alerts. 
 
## OneFuzz Information
- Onefuzz version: 5.3.0

## Service Exception Information
- Exception Type: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException
- Message: 
```
Result: Failure
Exception: AzureException: Could not find a suitable TLS CA certificate bundle, invalid path: /home/site/wwwroot/.python_packages/lib/site-packages/certifi/cacert.pem
Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 402, in _handle__invocation_request
call_result = await self._loop.run_in_executor(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 611, in _run_sync_func
return ExtensionManager.get_sync_invocation_wrapper(context,
File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper
result = function(**args)
File "/home/site/wwwroot/queue_file_changes/__init__.py", line 38, in main
File "/home/site/wwwroot/queue_file_changes/__init__.py", line 25, in file_added
File "/home/site/wwwroot/onefuzzlib/notifications/main.py", line 129, in new_files
File "/home/site/wwwroot/.python_packages/lib/site-packages/memoization/caching/plain_cache.py", line 42, in wrapper
File "/home/site/wwwroot/onefuzzlib/notifications/main.py", line 93, in get_notifications
File "/home/site/wwwroot/onefuzzlib/orm.py", line 466, in search
File "/home/site/wwwroot/.python_packages/lib/site-packages/memoization/caching/plain_cache.py", line 42, in wrapper
File "/home/site/wwwroot/onefuzzlib/azure/table.py", line 27, in get_client
File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/tableservice.py", line 565, in exists
File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/tableservice.py", line 1106, in _perform_request
File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/common/storageclient.py", line 430, in _perform_request
File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/common/storageclient.py", line 361, in _perform_request
```
- Time of the Error: 2022-05-08T10:41:35.711Z
- Operation Name: queue_file_changes

 

AB#39956433

**Comment by stishkin** [comment] 2022-06-24 20:36
Dupe of 1923

**Closed by stishkin** 2022-06-24 20:36 UTC
Labels: bug
