### ISSUE TITLE
Consider using different codes for misc. task failures

### ISSUE THREAD

**Issue by DrChat** [microsoft/onefuzz#2833] opened 2023-02-14 18:51 UTC
There are several task-related failures in `TaskOperations.cs` that all get reported with `ErrorCode.TASK_FAILED` (468).
For example:
https://github.com/microsoft/onefuzz/blob/0c58a59011afc1e4cbbfe26e33f5e2fa0d79f034/src/ApiService/ApiService/onefuzzlib/TaskOperations.cs#L134-L136

Instead of using the same failure code for all of these errors, it would be more convenient if they were assigned unique values so that they may be more easily filtered.

For example, in our setup we spawn two tasks where one depends on the other. When one fails, we always get an error from the other stating that the prerequisite task failed.
It'd be better if we could simply filter out the prerequisite task failure messages since they do not contain any useful information.

AB#36092

**Comment by stishkin** [comment] 2023-02-15 21:57
Related/Duplicate: 

https://github.com/microsoft/onefuzz/issues/2213

**Comment by mgreisen** [comment] 2023-03-27 14:42
Closing as a duplicate of https://github.com/microsoft/onefuzz/issues/2213
I've added the comments from this issue to that one.

**Closed by mgreisen** 2023-03-27 14:42 UTC
Labels: enhancement
